In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("fifa21_raw_data.csv")
df

C:\Users\Nischay Yedery\AppData\Local\Temp\ipykernel_20336\1999500042.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("fifa21_raw_data.csv")

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,2

In [4]:
df['Team & Contract']= df['Team & Contract'].str.strip('\n\n\n\n')

In [5]:
df['Team & Contract']

0                               FC Barcelona\n2004 ~ 2021
1                                   Juventus\n2018 ~ 2022
2                            Atlético Madrid\n2014 ~ 2023
3                            Manchester City\n2015 ~ 2023
4                        Paris Saint-Germain\n2017 ~ 2022
                               ...
18974    Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020
18975                        Oldham Athletic\n2020 ~ 2021
18976                             Wuhan Zall\n2018 ~ 2022
18977                        Oldham Athletic\n2020 ~ 2021
18978                           Club Bolívar\n2020 ~ 2024
Name: Team & Contract, Length: 18979, dtype: object

In [6]:
df['Team & Contract'].str.split('\n')

0                              [FC Barcelona, 2004 ~ 2021]
1                                  [Juventus, 2018 ~ 2022]
2                           [Atlético Madrid, 2014 ~ 2023]
3                           [Manchester City, 2015 ~ 2023]
4                       [Paris Saint-Germain, 2017 ~ 2022]
                               ...
18974    [Chongqing Dangdai Lifan FC SWM Team, 2020 ~ 2...
18975                       [Oldham Athletic, 2020 ~ 2021]
18976                            [Wuhan Zall, 2018 ~ 2022]
18977                       [Oldham Athletic, 2020 ~ 2021]
18978                          [Club Bolívar, 2020 ~ 2024]
Name: Team & Contract, Length: 18979, dtype: object

In [7]:
df['Club']=df['Team & Contract'].str.split('\n').str[0]

In [8]:
df['Contract']=df['Team & Contract'].str.split('\n').str[1]

In [9]:
df

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [10]:
df= df.drop(columns='photoUrl')
df

,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,158023,...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,20801,...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,200389,...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,192985,...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,190871,...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,257710,...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,258736,...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,247223,...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,258760,...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,255958,...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [11]:
df=df.drop(columns='playerUrl')
df

,LongName,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,158023,"5'7""",...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,20801,"6'2""",...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,200389,"6'2""",...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,192985,"5'11""",...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,190871,"5'9""",...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,257710,"5'10""",...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,258736,"5'7""",...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,247223,"5'10""",...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,Ben Hough,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,258760,"5'9""",...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,255958,"5'9""",...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [12]:
df=df.drop_duplicates()
df

,LongName,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,158023,"5'7""",...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,20801,"6'2""",...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,200389,"6'2""",...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,192985,"5'11""",...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,190871,"5'9""",...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,257710,"5'10""",...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,258736,"5'7""",...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,247223,"5'10""",...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,Ben Hough,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,258760,"5'9""",...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,255958,"5'9""",...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [13]:
df.shape

(18978, 77)

In [14]:
df.describe()

,Age,↓OVA,POT,ID,BOV,Growth,Attacking,Crossing,Finishing,Heading Accuracy,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,...,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000,18978.000000
mean,25.194225,65.718042,71.135789,226403.457477,66.751080,5.417747,248.935610,49.687375,45.842871,51.941459,...,16.217620,16.519654,1595.272368,355.699652,67.453683,53.457582,57.680472,62.874750,49.864738,64.368427
std,4.710618,6.968701,6.114189,27141.767404,6.746785,5.663967,74.300567,18.131089,19.567492,17.293983,...,17.002582,17.854549,269.874424,40.760683,10.678065,13.827581,10.081845,9.927607,16.442378,9.601882
min,16.000000,47.000000,47.000000,41.000000,48.000000,0.000000,42.000000,6.000000,3.000000,5.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,21.000000,61.000000,67.000000,210134.500000,62.000000,0.000000,222.000000,38.000000,30.000000,44.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,25.000000,66.000000,71.000000,232421.000000,67.000000,4.000000,263.000000,54.000000,49.000000,55.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,29.000000,70.000000,75.000000,246922.750000,71.000000,9.000000,297.000000,63.000000,62.000000,64.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,53.000000,93.000000,95.000000,259216.000000,93.000000,26.000000,437.000000,94.000000,95.000000,93.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [15]:
df.columns

Index(['LongName', 'Nationality', 'Positions', 'Name', 'Age', '↓OVA', 'POT',
       'Team & Contract', 'ID', 'Height', 'Weight', 'foot', 'BOV', 'BP',
       'Growth', 'Joined', 'Loan Date End', 'Value', 'Wage', 'Release Clause',
       'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve',
       'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Club', 'Contract'],
      dtype='object')

In [16]:
df=df.rename(columns={'↓OVA':'OVA'})
df

,LongName,Nationality,Positions,Name,Age,OVA,POT,Team & Contract,ID,Height,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,158023,"5'7""",...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,20801,"6'2""",...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,200389,"6'2""",...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,192985,"5'11""",...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,190871,"5'9""",...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,257710,"5'10""",...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,258736,"5'7""",...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,247223,"5'10""",...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,Ben Hough,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,258760,"5'9""",...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,255958,"5'9""",...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [17]:
df= df.drop(columns='Team & Contract')
df

,LongName,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,158023,"5'7""",159lbs,...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,"6'2""",183lbs,...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,200389,"6'2""",192lbs,...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,"5'11""",154lbs,...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,190871,"5'9""",150lbs,...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,257710,"5'10""",154lbs,...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,258736,"5'7""",128lbs,...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,247223,"5'10""",146lbs,...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,Ben Hough,England,CM,B. Hough,17,47,67,258760,"5'9""",143lbs,...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,255958,"5'9""",150lbs,...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [18]:
df=df.drop(columns='LongName')
df

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,foot,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,"5'7""",159lbs,Left,...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,"6'2""",183lbs,Right,...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Slovenia,GK,J. Oblak,27,91,93,200389,"6'2""",192lbs,Right,...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,"5'11""",154lbs,Right,...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,"5'9""",150lbs,Right,...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,"5'10""",154lbs,Right,...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,England,ST,V. Da Silva,17,47,67,258736,"5'7""",128lbs,Right,...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,China PR,CB,Xia Ao,21,47,55,247223,"5'10""",146lbs,Right,...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,England,CM,B. Hough,17,47,67,258760,"5'9""",143lbs,Right,...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Bolivia,CDM,M. Flores,19,47,63,255958,"5'9""",150lbs,Right,...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [19]:
df.isnull().any()

Nationality    False
Positions      False
Name           False
Age            False
OVA            False
               ...
DEF            False
PHY            False
Hits           False
Club           False
Contract       False
Length: 75, dtype: bool

In [20]:
def lbs_to_kg(x):
    if "lbs" in x:
        lbs=x.replace("lbs","")
        kilograms=round(int(lbs)/2.2,0)
        return int(kilograms)
    else:
        return int(x)

In [21]:
df['Weight']=df['Weight'].apply(lbs_to_kg)
df['Weight'].unique()

array([ 72,  83,  87,  70,  68,  80,  73,  91,  71,  69,  92,  85,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  88,  93,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99,  56, 102, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52], dtype=int64)

In [22]:
df.rename(columns={'Weight':'Weight_In_Kg'})

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight_In_Kg,foot,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,"5'7""",72,Left,...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,"6'2""",83,Right,...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Slovenia,GK,J. Oblak,27,91,93,200389,"6'2""",87,Right,...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,"5'11""",70,Right,...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,"5'9""",68,Right,...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,"5'10""",70,Right,...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,England,ST,V. Da Silva,17,47,67,258736,"5'7""",58,Right,...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,China PR,CB,Xia Ao,21,47,55,247223,"5'10""",66,Right,...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,England,CM,B. Hough,17,47,67,258760,"5'9""",65,Right,...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Bolivia,CDM,M. Flores,19,47,63,255958,"5'9""",68,Right,...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [23]:
def ft_to_cm(x):
    if "'" in x:
        ft=x.replace("'",".").replace('"',"")
        cm= round(float(ft)*30.48,0)
        return int(cm)

    else:
        return int(x)

df["Height"]=df["Height"].apply(ft_to_cm)
df["Height"].unique()

array([174, 189, 156, 180, 183, 155, 192, 195, 186, 201, 177, 171, 198,
       168, 165, 204, 158, 162, 207, 210], dtype=int64)

In [24]:
df.rename(columns={'Height':'Height_in_cm'})

,Nationality,Positions,Name,Age,OVA,POT,ID,Height_in_cm,Weight,foot,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,174,72,Left,...,5 ★,85,92,91,95,38,65,\n372,FC Barcelona,2004 ~ 2021
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,189,83,Right,...,5 ★,89,93,81,89,35,77,\n344,Juventus,2018 ~ 2022
2,Slovenia,GK,J. Oblak,27,91,93,200389,189,87,Right,...,3 ★,87,92,78,90,52,90,\n86,Atlético Madrid,2014 ~ 2023
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,156,70,Right,...,4 ★,76,86,93,88,64,78,\n163,Manchester City,2015 ~ 2023
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,180,68,Right,...,5 ★,91,85,86,94,36,59,\n273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,155,70,Right,...,1 ★,58,23,26,27,50,48,2,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,England,ST,V. Da Silva,17,47,67,258736,174,58,Right,...,1 ★,70,46,40,53,16,40,3,Oldham Athletic,2020 ~ 2021
18976,China PR,CB,Xia Ao,21,47,55,247223,155,66,Right,...,1 ★,64,28,26,38,48,51,3,Wuhan Zall,2018 ~ 2022
18977,England,CM,B. Hough,17,47,67,258760,180,65,Right,...,1 ★,64,40,48,49,35,45,5,Oldham Athletic,2020 ~ 2021
18978,Bolivia,CDM,M. Flores,19,47,63,255958,180,68,Right,...,1 ★,57,32,43,48,44,49,2,Club Bolívar,2020 ~ 2024

In [25]:
df['Hits']=df['Hits'].str.lstrip('\n')

In [26]:
df.isnull().any()

Nationality    False
Positions      False
Name           False
Age            False
OVA            False
               ...
DEF            False
PHY            False
Hits            True
Club           False
Contract       False
Length: 75, dtype: bool

In [27]:
df.columns

Index(['Nationality', 'Positions', 'Name', 'Age', 'OVA', 'POT', 'ID', 'Height',
       'Weight', 'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Club', 'Contract'],
      dtype='object')

In [28]:
df[['Value','Wage','Release Clause']].head()

    Value   Wage Release Clause
0  €67.5M  €560K        €138.4M
1    €46M  €220K         €75.9M
2    €75M  €125K        €159.4M
3    €87M  €370K          €161M
4    €90M  €270K        €166.5M

In [29]:
def money(x):
    if "€" in x:
        x = x.replace("€", "")

    if "M" in x:
        x = x.replace("M", "")
        return int(float(x) * 1_000_000)

    elif "K" in x:
        x = x.replace("K", "")
        return int(float(x) * 1_000)

    return int(x)

In [30]:
df["Value"] = df["Value"].apply(money) / 1_000_000
df["Wage"] = df["Wage"].apply(money)
df["Release Clause"] = df["Release Clause"].apply(money) / 1_000_000

df=df.rename(columns={"Value": "Values in Euro Million","Wage": "Wage in Euros","Release Clause": "Release Clause in Euro Million"})

In [31]:
df

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,foot,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club,Contract
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,174,72,Left,...,5 ★,85,92,91,95,38,65,372,FC Barcelona,2004 ~ 2021
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,189,83,Right,...,5 ★,89,93,81,89,35,77,344,Juventus,2018 ~ 2022
2,Slovenia,GK,J. Oblak,27,91,93,200389,189,87,Right,...,3 ★,87,92,78,90,52,90,86,Atlético Madrid,2014 ~ 2023
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,156,70,Right,...,4 ★,76,86,93,88,64,78,163,Manchester City,2015 ~ 2023
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,180,68,Right,...,5 ★,91,85,86,94,36,59,273,Paris Saint-Germain,2017 ~ 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,155,70,Right,...,1 ★,58,23,26,27,50,48,NaN,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020
18975,England,ST,V. Da Silva,17,47,67,258736,174,58,Right,...,1 ★,70,46,40,53,16,40,NaN,Oldham Athletic,2020 ~ 2021
18976,China PR,CB,Xia Ao,21,47,55,247223,155,66,Right,...,1 ★,64,28,26,38,48,51,NaN,Wuhan Zall,2018 ~ 2022
18977,England,CM,B. Hough,17,47,67,258760,180,65,Right,...,1 ★,64,40,48,49,35,45,NaN,Oldham Athletic,2020 ~ 2021
18978,Bolivia,CDM,M. Flores,19,47,63,255958,180,68,Right,...,1 ★,57,32,43,48,44,49,NaN,Club Bolívar,2020 ~ 2024

In [32]:
df[['W/F','SM','IR']]

       W/F  SM   IR
0      4 ★  4★  5 ★
1      4 ★  5★  5 ★
2      3 ★  1★  3 ★
3      5 ★  4★  4 ★
4      5 ★  5★  5 ★
...    ...  ..  ...
18974  2 ★  2★  1 ★
18975  2 ★  2★  1 ★
18976  2 ★  2★  1 ★
18977  2 ★  2★  1 ★
18978  3 ★  2★  1 ★

[18978 rows x 3 columns]

In [33]:
df['W/F'] = df['W/F'].str.replace('★','')
df['SM'] = df['SM'].str.replace('★','')
df['IR'] = df['IR'].str.replace('★','')

In [34]:
df[['W/F','SM','IR']]

      W/F SM  IR
0      4   4  5
1      4   5  5
2      3   1  3
3      5   4  4
4      5   5  5
...    .. ..  ..
18974  2   2  1
18975  2   2  1
18976  2   2  1
18977  2   2  1
18978  3   2  1

[18978 rows x 3 columns]

In [35]:
df = df.rename(columns = {'W/F':'W/F Ratings'})
df = df.rename(columns = {'SM':'SM Ratings'})
df = df.rename(columns = {'IR':'IR Ratings'})

In [36]:
df.Contract.unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2018 ~ 2024', '2017 ~ 2023', '2016 ~ 2023',
       '2018 ~ 2023', '2014 ~ 2022', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2019 ~ 2024', '2012 ~ 2021',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2016 ~ 2025', '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022',
       '2012 ~ 2022', '2012 ~ 2023', '2013 ~ 2022', '2011 ~ 2022',
       '2012 ~ 2024', '2016 ~ 2021', '2019 ~ 2022', '2008 ~ 2022',
       '2013 ~ 2024', '2017 ~ 2021', '2020 ~ 2024', '2010 ~ 2022',
       '2011 ~ 2024', '2020 ~ 2023', '2020 ~ 2021', '2014 ~ 2024',
       '2016 ~ 2022', '2013 ~ 2026', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 2028',
       '2010 ~ 2023', '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026',
       '2012 ~ 2025', '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027',
       '2013 ~ 2025', 'Dec 31, 2020 On Loan', '2011 ~ 2025',
       '2019 ~ 2020', '2016 ~ 2020', '2007 ~ 2021', '2020 ~ 2026',
       '2010 ~ 2025', '2009 ~ 2023', '2020 ~ 2020', '2008 ~ 2021',
       '2016 ~ 2026', '2012 ~ 2020', 'Jan 30, 2021 On Loan',
       '2014 ~ 2025', '2015 ~ 2020', 'Jun 30, 2022 On Loan',
       'May 31, 2021 On Loan', '2018 ~ 2020', '2013 ~ 2020',
       '2014 ~ 2020', '2006 ~ 2024', 'Jul 5, 2021 On Loan',
       'Dec 31, 2021 On Loan', '2011 ~ 2020', '2004 ~ 2025',
       'Jul 1, 2021 On Loan', 'Jan 1, 2021 On Loan', '2006 ~ 2023',
       '2006 ~ 2021', 'Aug 31, 2021 On Loan', '2005 ~ 2023',
       '2003 ~ 2020', '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020',
       '2005 ~ 2022', 'Jan 31, 2021 On Loan', '2010 ~ 2020',
       'Dec 30, 2021 On Loan', '2008 ~ 2020', '2007 ~ 2020',
       '2003 ~ 2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002 ~ 2021', 'Jan 17, 2021 On Loan',
       '1998 ~ 2021', 'Jun 30, 2023 On Loan', '2003 ~ 2022',
       '2007 ~ 2023', 'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006 ~ 2020', 'Dec 30, 2020 On Loan',
       '2007 ~ 2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004 ~ 2020', '2009 ~ 2025', 'Aug 1, 2021 On Loan'], dtype=object)

In [37]:
from datetime import datetime

In [38]:
def type(x):
    if 'Free' in x:
        return "Free"
    if "Loan" in x:
        return "Loan"
    if "~" in x:
        return "Contract"
    else:
        return pd.na

In [66]:
def start_time_contract(x):
    if '~' in x:
        return int(x[:4])
    if "Loan" in x:
        # Replace both lowercase and uppercase variations if needed
        x = x.replace(" on Loan", "")
        x = x.replace(" On Loan", "")
        x = x.strip()
        # Now parse the date
        x = datetime.strptime(x, "%b %d, %Y")
        return x.date()
    else:
        return pd.NA
    
def end_time_contract(type,contract,loan):
    if type == "Contract":
        return int(contract[-4:])
    if type == "Loan":
        loan = datetime.strptime(loan, "%b %d, %Y")
        return loan.date()
    else:
        return pd.NA

In [62]:
df["Type of contract"] = df["Contract"].apply(type)

In [63]:
df["End year"] = df.apply(lambda row: end_time_contract(row["Type of contract"],row["Contract"],row["Loan Date End"] ), axis=1)

In [67]:
df["Start year"] = df["Contract"].apply(start_time_contract)

In [68]:
df

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,foot,...,PAS,DRI,DEF,PHY,Hits,Club,Contract,Type of contract,Start year,End year
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,174,72,Left,...,91,95,38,65,372,FC Barcelona,2004 ~ 2021,Contract,2004,2021
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,189,83,Right,...,81,89,35,77,344,Juventus,2018 ~ 2022,Contract,2018,2022
2,Slovenia,GK,J. Oblak,27,91,93,200389,189,87,Right,...,78,90,52,90,86,Atlético Madrid,2014 ~ 2023,Contract,2014,2023
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,156,70,Right,...,93,88,64,78,163,Manchester City,2015 ~ 2023,Contract,2015,2023
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,180,68,Right,...,86,94,36,59,273,Paris Saint-Germain,2017 ~ 2022,Contract,2017,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,155,70,Right,...,26,27,50,48,NaN,Chongqing Dangdai Lifan FC SWM Team,2020 ~ 2020,Contract,2020,2020
18975,England,ST,V. Da Silva,17,47,67,258736,174,58,Right,...,40,53,16,40,NaN,Oldham Athletic,2020 ~ 2021,Contract,2020,2021
18976,China PR,CB,Xia Ao,21,47,55,247223,155,66,Right,...,26,38,48,51,NaN,Wuhan Zall,2018 ~ 2022,Contract,2018,2022
18977,England,CM,B. Hough,17,47,67,258760,180,65,Right,...,48,49,35,45,NaN,Oldham Athletic,2020 ~ 2021,Contract,2020,2021
18978,Bolivia,CDM,M. Flores,19,47,63,255958,180,68,Right,...,43,48,44,49,NaN,Club Bolívar,2020 ~ 2024,Contract,2020,2024

In [71]:
df.drop(columns='Contract',inplace =True)

In [72]:
df

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,foot,...,SHO,PAS,DRI,DEF,PHY,Hits,Club,Type of contract,Start year,End year
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,174,72,Left,...,92,91,95,38,65,372,FC Barcelona,Contract,2004,2021
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,189,83,Right,...,93,81,89,35,77,344,Juventus,Contract,2018,2022
2,Slovenia,GK,J. Oblak,27,91,93,200389,189,87,Right,...,92,78,90,52,90,86,Atlético Madrid,Contract,2014,2023
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,156,70,Right,...,86,93,88,64,78,163,Manchester City,Contract,2015,2023
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,180,68,Right,...,85,86,94,36,59,273,Paris Saint-Germain,Contract,2017,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,155,70,Right,...,23,26,27,50,48,NaN,Chongqing Dangdai Lifan FC SWM Team,Contract,2020,2020
18975,England,ST,V. Da Silva,17,47,67,258736,174,58,Right,...,46,40,53,16,40,NaN,Oldham Athletic,Contract,2020,2021
18976,China PR,CB,Xia Ao,21,47,55,247223,155,66,Right,...,28,26,38,48,51,NaN,Wuhan Zall,Contract,2018,2022
18977,England,CM,B. Hough,17,47,67,258760,180,65,Right,...,40,48,49,35,45,NaN,Oldham Athletic,Contract,2020,2021
18978,Bolivia,CDM,M. Flores,19,47,63,255958,180,68,Right,...,32,43,48,44,49,NaN,Club Bolívar,Contract,2020,2024

In [73]:
df['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [74]:
df=df[list(df.columns[:7])+list(df.columns[-3:])+list(df.columns[8:-3])]
df=df.drop(columns=["Loan Date End"])

In [75]:
df[['Type of contract','Start year','End year']]

      Type of contract Start year End year
0             Contract       2004     2021
1             Contract       2018     2022
2             Contract       2014     2023
3             Contract       2015     2023
4             Contract       2017     2022
...                ...        ...      ...
18974         Contract       2020     2020
18975         Contract       2020     2021
18976         Contract       2018     2022
18977         Contract       2020     2021
18978         Contract       2020     2024

[18978 rows x 3 columns]

In [76]:
df[['Attacking','Skill','Movement','Power','Mentality','Defending','Goalkeeping']]

       Attacking  Skill  Movement  Power  Mentality  Defending  Goalkeeping
0            429    470       451    389        347         91           54
1            437    414       431    444        353         84           58
2             95    109       307    268        140         57          437
3            407    441       398    408        408        186           56
4            408    448       453    357        356         94           59
...          ...    ...       ...    ...        ...        ...          ...
18974        141    111       279    223        179        148           53
18975        202    208       339    231        186         42           48
18976        145    142       294    221        192        147           45
18977        211    219       305    226        193        116           45
18978        191    198       298    223        206        129           56

[18978 rows x 7 columns]

In [78]:
df["Attacking"]=round(df["Attacking"]/5,0)
df["Attacking"]=df["Attacking"].astype("int64")

df["Skill"]=df["Skill"]/5
df["Skill"]=df["Skill"].astype("int64")


df["Movement"]=df["Movement"]/5
df["Movement"]=df["Movement"].astype("int64")


df["Power"]=df["Power"]/5
df["Power"]=df["Power"].astype("int64")


df["Mentality"]=df["Mentality"]/6
df["Mentality"]=df["Mentality"].astype("int64")

df["Defending"]=df["Defending"]/3
df["Defending"]=df["Defending"].astype("int64")

df["Goalkeeping"] = df["Goalkeeping"]/5
df["Goalkeeping"] = df["Goalkeeping"].astype("int64")

In [79]:
df=df.rename(columns={"Attacking":"Attacking AVG", "Skill":"Skill AVG", "Movement":"Movement AVG",
                    "Power":"Power AVG", "Mentality":"Mentality AVG", "Defending":"Defending AVG", "Goalkeeping":"Goalkeeping AVG"} )

In [80]:
df

,Nationality,Positions,Name,Age,OVA,POT,ID,Type of contract,Start year,End year,...,D/W,IR Ratings,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Club
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,Contract,2004,2021,...,Low,5,85,92,91,95,38,65,372,FC Barcelona
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,Contract,2018,2022,...,Low,5,89,93,81,89,35,77,344,Juventus
2,Slovenia,GK,J. Oblak,27,91,93,200389,Contract,2014,2023,...,Medium,3,87,92,78,90,52,90,86,Atlético Madrid
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,Contract,2015,2023,...,High,4,76,86,93,88,64,78,163,Manchester City
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,Contract,2017,2022,...,Medium,5,91,85,86,94,36,59,273,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,Contract,2020,2020,...,Low,1,58,23,26,27,50,48,NaN,Chongqing Dangdai Lifan FC SWM Team
18975,England,ST,V. Da Silva,17,47,67,258736,Contract,2020,2021,...,Medium,1,70,46,40,53,16,40,NaN,Oldham Athletic
18976,China PR,CB,Xia Ao,21,47,55,247223,Contract,2018,2022,...,Medium,1,64,28,26,38,48,51,NaN,Wuhan Zall
18977,England,CM,B. Hough,17,47,67,258760,Contract,2020,2021,...,Medium,1,64,40,48,49,35,45,NaN,Oldham Athletic
18978,Bolivia,CDM,M. Flores,19,47,63,255958,Contract,2020,2024,...,Medium,1,57,32,43,48,44,49,NaN,Club Bolívar

In [81]:
 df['Hits'].unique()

array(['372', '344', '86', '163', '273', '182', '646', '79', '164', '170',
       '93', '131', '89', '90', '169', '187', '103', '317', '239', '56',
       '130', '229', '124', '172', '114', '46', '663', '479', '203',
       '198', '122', '565', '152', '140', '276', '209', '25', '136',
       '109', '139', '42', '99', '137', '166', '80', '104', '150', '112',
       '285', '133', '96', '69', '143', '100', '38', '83', '67', '207',
       '416', '315', '206', '424', '191', '454', '271', '249', '121',
       '246', '171', '148', '329', '70', '97', '73', '210', '82', '146',
       '62', '165', '129', '162', '35', '65', '47', '77', '106', '84',
       '1.3K', '310', '181', '364', '200', '141', '134', '259', '309',
       '367', '224', '211', '60', '176', '108', '63', '111', '52', '59',
       '350', '54', '117', '27', '91', '365', '312', '286', '157', '291',
       '245', '258', '233', '767', '288', '57', '115', '123', '142',
       '149', '227', '75', '53', '113', '71', '92', '144', '132', '125',
       '45', '158', '55', '43', '107', '24', '212', '21', '87', '39',
       '98', '192', '391', '23', '26', '13', '185', '177', '272', '193',
       '225', '78', '88', '37', '168', '85', '34', '1.5K', '48', '32',
       '215', '41', '20', '61', '68', '58', '19', '186', '17', '241',
       '574', '338', '274', '2.9K', '492', '670', '324', '352', '31',
       '30', '300', '189', '595', '127', '173', '159', '49', '36', '102',
       '280', '12', '14', '50', '76', '95', '51', '40', '22', '11', '9',
       '16', '10', '5', '222', '303', '268', '434', '256', '247', '248',
       '354', '289', '269', '237', '183', '6', '217', '155', '523', '921',
       '264', '72', '29', '476', '28', '205', '81', '393', '147', '74',
       '66', '33', '44', '314', '428', '261', '199', '281', '316', '118',
       '411', '396', '4', '794', '243', '204', '219', '167', '18', '356',
       '120', '561', '8', '101', '984', '2K', '603', '526', '1K', '343',
       '190', '154', '673', '194', '556', '128', '161', '494', '196',
       '232', '332', '283', '138', '15', '64', '94', '3', '7', '308',
       '382', '345', '275', '313', '398', '153', '935', '201', '699',
       '758', '745', '184', '1', '501', '145', '119', '255', '1.2K', '2',
       '253', '1.7K', '156', '238', '221', '175', '151', '500', '731',
       '532', '466', '535', '297', '265', '599', '234', '180', '195',
       '116', '423', '266', '560', '188', '244', '216', '496', '257',
       '226', '105', '412', '220', '970', '135', '360', '178', '1.1K',
       '326', '251', '369', '4.5K', '681', '700', '477', '333', '1.9K',
       '174', '406', '358', '555', '335', '856', '1.8K', '230', '250',
       '792', '400', '126', '342', '270', '529', '445', '830', '380',
       '881', '240', '160', '378', '598', '433', '202', nan], dtype=object)

In [82]:
def convert_hits(x):
    if pd.isna(x):
        return np.nan
    elif 'K' in str(x):
        return float(x[:-1])
    else:
        return float(x)

df['Hits in K'] = df['Hits'].apply(convert_hits)

df.drop(columns=['Hits'], inplace=True)

print(df['Hits in K'].head(10))

0    372.0
1    344.0
2     86.0
3    163.0
4    273.0
5    182.0
6    646.0
7     79.0
8    164.0
9    170.0
Name: Hits in K, dtype: float64

In [83]:
df['Hits in K'].isnull().sum()

2595

In [84]:
df.fillna({'Hits in K': df['Hits in K'].mean()}, inplace=True)

In [85]:
df

,Nationality,Positions,Name,Age,OVA,POT,ID,Type of contract,Start year,End year,...,D/W,IR Ratings,PAC,SHO,PAS,DRI,DEF,PHY,Club,Hits in K
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,Contract,2004,2021,...,Low,5,85,92,91,95,38,65,FC Barcelona,372.000000
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,Contract,2018,2022,...,Low,5,89,93,81,89,35,77,Juventus,344.000000
2,Slovenia,GK,J. Oblak,27,91,93,200389,Contract,2014,2023,...,Medium,3,87,92,78,90,52,90,Atlético Madrid,86.000000
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,Contract,2015,2023,...,High,4,76,86,93,88,64,78,Manchester City,163.000000
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,Contract,2017,2022,...,Medium,5,91,85,86,94,36,59,Paris Saint-Germain,273.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,Contract,2020,2020,...,Low,1,58,23,26,27,50,48,Chongqing Dangdai Lifan FC SWM Team,17.524721
18975,England,ST,V. Da Silva,17,47,67,258736,Contract,2020,2021,...,Medium,1,70,46,40,53,16,40,Oldham Athletic,17.524721
18976,China PR,CB,Xia Ao,21,47,55,247223,Contract,2018,2022,...,Medium,1,64,28,26,38,48,51,Wuhan Zall,17.524721
18977,England,CM,B. Hough,17,47,67,258760,Contract,2020,2021,...,Medium,1,64,40,48,49,35,45,Oldham Athletic,17.524721
18978,Bolivia,CDM,M. Flores,19,47,63,255958,Contract,2020,2024,...,Medium,1,57,32,43,48,44,49,Club Bolívar,17.524721